version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./build/django/Dockerfile
    ports:
    - "7000:7000"
    volumes:
    - /home/CMS
    command: python3 /home/CMS/manage.py runserver 0.0.0.0:7000

  nginx:
    build: ./build/nginx/
    ports:
    - "70:70"
    - "7001:7001"
    network_mode: "host"
    volumes:
    - ./CMS/static:/usr/share/nginx/html/static:ro
    restart: always
