# Generated by Django 2.2.2 on 2020-07-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('illegal_situation', models.TextField()),
                ('commercial_housing_situation', models.TextField()),
                ('rental_status', models.TextField()),
                ('object_class', models.TextField()),
                ('vehicle_condition', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellation', models.TextField()),
                ('name', models.TextField()),
                ('domicile', models.TextField()),
                ('work_units', models.TextField()),
                ('id_number', models.TextField(unique=True)),
                ('income', models.TextField()),
                ('social_security', models.TextField()),
                ('political_landscape', models.TextField()),
                ('health', models.TextField()),
                ('phone_number', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.Family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.Person')),
            ],
            options={
                'db_table': 'person_family_relationship',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ManyToManyField(through='CMS.PersonFamily', to='CMS.Family'),
        ),
        migrations.CreateModel(
            name='HandleAffairsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('agent', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.Family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CMS.Person')),
            ],
        ),
    ]
